apiVersion: apps/v1
kind: Deployment
metadata:
  name: earnings-model-service
  labels:
    app: earnings-model-service
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: earnings-model-service
  replicas: 2
  template:
    metadata:
      labels:
        app: earnings-model-service
    spec:
      containers:
      - name: model-service
        image: localhost:32000/earnings-model-service
        ports:
        - containerPort: 8084
        env:
        - name: APP_NAME
          value: EARNINGS
