apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-model-service
  labels:
    app: ts-model-service
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: ts-model-service
  replicas: 2
  template:
    metadata:
      labels:
        app: ts-model-service
    spec:
      containers:
      - name: ts-model-service
        image: localhost:32000/ts-model-service
        ports:
        - containerPort: 8085
        env:
          - name: APP_NAME
            value: TS-MODEL
        volumeMounts:
          - mountPath: "/cache/model-storage"
            name: model-storage
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-claim
