
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-storage-claim
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi