apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-model-service
  labels:
    app: load-model-service
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: load-model-service
  replicas: 2
  template:
    metadata:
      labels:
        app: load-model-service
    spec:
      containers:
      - name: model-service
        image: localhost:32000/load-model-service
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: LOAD
